/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGovernment__factory } from "./IGovernment__factory";
export { IMedical__factory } from "./IMedical__factory";
export { ISocialNetwork__factory } from "./ISocialNetwork__factory";
