/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { Government__factory } from "./Government__factory";
export { Medical__factory } from "./Medical__factory";
export { SocialNetwork__factory } from "./SocialNetwork__factory";
