/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governmentExampleSol from "./GovernmentExample.sol";
export * as medicalExampleSol from "./MedicalExample.sol";
export * as socialNetworkExampleSol from "./SocialNetworkExample.sol";
export * as interfaces from "./interfaces";
