/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export declare namespace Medical {
  export type DoctorStruct = {
    ownerAddress: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    id: PromiseOrValue<BigNumberish>;
  };

  export type DoctorStructOutput = [string, string, BigNumber] & {
    ownerAddress: string;
    name: string;
    id: BigNumber;
  };

  export type PatientStruct = {
    ownerAddress: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    bloodType: PromiseOrValue<string>;
    lastUpdate: PromiseOrValue<BigNumberish>;
    doctorAddress: PromiseOrValue<string>;
    id: PromiseOrValue<BigNumberish>;
  };

  export type PatientStructOutput = [
    string,
    string,
    string,
    BigNumber,
    string,
    BigNumber
  ] & {
    ownerAddress: string;
    name: string;
    bloodType: string;
    lastUpdate: BigNumber;
    doctorAddress: string;
    id: BigNumber;
  };
}

export interface MedicalInterface extends utils.Interface {
  functions: {
    "deleteDoctor()": FunctionFragment;
    "doctors(uint256)": FunctionFragment;
    "getMedicalData(address)": FunctionFragment;
    "isViewingAccessGranted(address,address)": FunctionFragment;
    "patients(uint256)": FunctionFragment;
    "provideViewingAccess(address)": FunctionFragment;
    "register(string,string)": FunctionFragment;
    "updateBloodType(string)": FunctionFragment;
    "updateDoctorInfo(address,string)": FunctionFragment;
    "updateName(string)": FunctionFragment;
    "viewAllDoctors()": FunctionFragment;
    "viewClientsList()": FunctionFragment;
    "viewDoctorProfile()": FunctionFragment;
    "viewPatientProfile()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "deleteDoctor"
      | "doctors"
      | "getMedicalData"
      | "isViewingAccessGranted"
      | "patients"
      | "provideViewingAccess"
      | "register"
      | "updateBloodType"
      | "updateDoctorInfo"
      | "updateName"
      | "viewAllDoctors"
      | "viewClientsList"
      | "viewDoctorProfile"
      | "viewPatientProfile"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deleteDoctor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "doctors",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMedicalData",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isViewingAccessGranted",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "patients",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "provideViewingAccess",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBloodType",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDoctorInfo",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "viewAllDoctors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewClientsList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewDoctorProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewPatientProfile",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doctors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMedicalData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isViewingAccessGranted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "patients", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "provideViewingAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBloodType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDoctorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "viewAllDoctors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewClientsList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewDoctorProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewPatientProfile",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Medical extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MedicalInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deleteDoctor(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    doctors(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        ownerAddress: string;
        name: string;
        id: BigNumber;
      }
    >;

    getMedicalData(
      _patientAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        name: string;
        bloodType: string;
        lastUpdatedtime: BigNumber;
      }
    >;

    isViewingAccessGranted(
      _patientAddress: PromiseOrValue<string>,
      _medicalProviderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    patients(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, BigNumber] & {
        ownerAddress: string;
        name: string;
        bloodType: string;
        lastUpdate: BigNumber;
        doctorAddress: string;
        id: BigNumber;
      }
    >;

    provideViewingAccess(
      _doctorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    register(
      _name: PromiseOrValue<string>,
      _bloodType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateBloodType(
      _bloodType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateDoctorInfo(
      _doctorAddress: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    viewAllDoctors(
      overrides?: CallOverrides
    ): Promise<[Medical.DoctorStructOutput[]]>;

    viewClientsList(
      overrides?: CallOverrides
    ): Promise<[Medical.PatientStructOutput[]]>;

    viewDoctorProfile(
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string]>;

    viewPatientProfile(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, string, string]>;
  };

  deleteDoctor(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  doctors(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber] & {
      ownerAddress: string;
      name: string;
      id: BigNumber;
    }
  >;

  getMedicalData(
    _patientAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber] & {
      name: string;
      bloodType: string;
      lastUpdatedtime: BigNumber;
    }
  >;

  isViewingAccessGranted(
    _patientAddress: PromiseOrValue<string>,
    _medicalProviderAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  patients(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string, BigNumber] & {
      ownerAddress: string;
      name: string;
      bloodType: string;
      lastUpdate: BigNumber;
      doctorAddress: string;
      id: BigNumber;
    }
  >;

  provideViewingAccess(
    _doctorAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  register(
    _name: PromiseOrValue<string>,
    _bloodType: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateBloodType(
    _bloodType: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateDoctorInfo(
    _doctorAddress: PromiseOrValue<string>,
    _name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateName(
    _name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  viewAllDoctors(
    overrides?: CallOverrides
  ): Promise<Medical.DoctorStructOutput[]>;

  viewClientsList(
    overrides?: CallOverrides
  ): Promise<Medical.PatientStructOutput[]>;

  viewDoctorProfile(
    overrides?: CallOverrides
  ): Promise<[string, BigNumber, string]>;

  viewPatientProfile(
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, string, string]>;

  callStatic: {
    deleteDoctor(overrides?: CallOverrides): Promise<void>;

    doctors(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        ownerAddress: string;
        name: string;
        id: BigNumber;
      }
    >;

    getMedicalData(
      _patientAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber] & {
        name: string;
        bloodType: string;
        lastUpdatedtime: BigNumber;
      }
    >;

    isViewingAccessGranted(
      _patientAddress: PromiseOrValue<string>,
      _medicalProviderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    patients(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, BigNumber] & {
        ownerAddress: string;
        name: string;
        bloodType: string;
        lastUpdate: BigNumber;
        doctorAddress: string;
        id: BigNumber;
      }
    >;

    provideViewingAccess(
      _doctorAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    register(
      _name: PromiseOrValue<string>,
      _bloodType: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBloodType(
      _bloodType: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDoctorInfo(
      _doctorAddress: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateName(
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    viewAllDoctors(
      overrides?: CallOverrides
    ): Promise<Medical.DoctorStructOutput[]>;

    viewClientsList(
      overrides?: CallOverrides
    ): Promise<Medical.PatientStructOutput[]>;

    viewDoctorProfile(
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string]>;

    viewPatientProfile(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, string, string]>;
  };

  filters: {};

  estimateGas: {
    deleteDoctor(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    doctors(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMedicalData(
      _patientAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isViewingAccessGranted(
      _patientAddress: PromiseOrValue<string>,
      _medicalProviderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    patients(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    provideViewingAccess(
      _doctorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    register(
      _name: PromiseOrValue<string>,
      _bloodType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateBloodType(
      _bloodType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateDoctorInfo(
      _doctorAddress: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    viewAllDoctors(overrides?: CallOverrides): Promise<BigNumber>;

    viewClientsList(overrides?: CallOverrides): Promise<BigNumber>;

    viewDoctorProfile(overrides?: CallOverrides): Promise<BigNumber>;

    viewPatientProfile(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deleteDoctor(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    doctors(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMedicalData(
      _patientAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isViewingAccessGranted(
      _patientAddress: PromiseOrValue<string>,
      _medicalProviderAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    patients(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    provideViewingAccess(
      _doctorAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    register(
      _name: PromiseOrValue<string>,
      _bloodType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateBloodType(
      _bloodType: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateDoctorInfo(
      _doctorAddress: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    viewAllDoctors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    viewClientsList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    viewDoctorProfile(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    viewPatientProfile(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
