/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGovernment } from "./IGovernment";
export type { IMedical } from "./IMedical";
export type { ISocialNetwork } from "./ISocialNetwork";
