/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import * as Contracts from ".";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";
import { ethers } from "ethers";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Government",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Government__factory>;
    getContractFactory(
      name: "IGovernment",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGovernment__factory>;
    getContractFactory(
      name: "IMedical",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMedical__factory>;
    getContractFactory(
      name: "ISocialNetwork",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISocialNetwork__factory>;
    getContractFactory(
      name: "Medical",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Medical__factory>;
    getContractFactory(
      name: "SocialNetwork",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SocialNetwork__factory>;

    getContractAt(
      name: "Government",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Government>;
    getContractAt(
      name: "IGovernment",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGovernment>;
    getContractAt(
      name: "IMedical",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMedical>;
    getContractAt(
      name: "ISocialNetwork",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISocialNetwork>;
    getContractAt(
      name: "Medical",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Medical>;
    getContractAt(
      name: "SocialNetwork",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SocialNetwork>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
