/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGovernment } from "./IGovernment";
export type { IMedical } from "./IMedical";
export type { ISocialNetwork } from "./ISocialNetwork";
export * as factories from "./factories";
export { IGovernment__factory } from "./factories/IGovernment__factory";
export { IMedical__factory } from "./factories/IMedical__factory";
export { ISocialNetwork__factory } from "./factories/ISocialNetwork__factory";
