/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as governmentExampleSol from "./GovernmentExample.sol";
import type * as medicalExampleSol from "./MedicalExample.sol";
import type * as socialNetworkExampleSol from "./SocialNetworkExample.sol";
import type * as interfaces from "./interfaces";

export type { governmentExampleSol };

export type { medicalExampleSol };

export type { socialNetworkExampleSol };

export type { interfaces };
export * as factories from "./factories";
export type { Government } from "./GovernmentExample.sol/Government";
export { Government__factory } from "./factories/GovernmentExample.sol/Government__factory";
export type { IGovernment } from "./interfaces/IGovernment";
export { IGovernment__factory } from "./factories/interfaces/IGovernment__factory";
export type { IMedical } from "./interfaces/IMedical";
export { IMedical__factory } from "./factories/interfaces/IMedical__factory";
export type { ISocialNetwork } from "./interfaces/ISocialNetwork";
export { ISocialNetwork__factory } from "./factories/interfaces/ISocialNetwork__factory";
export type { Medical } from "./MedicalExample.sol/Medical";
export { Medical__factory } from "./factories/MedicalExample.sol/Medical__factory";
export type { SocialNetwork } from "./SocialNetworkExample.sol/SocialNetwork";
export { SocialNetwork__factory } from "./factories/SocialNetworkExample.sol/SocialNetwork__factory";
